### ISSUE TITLE
Don't work with 1.16.0

### ISSUE THREAD

**Issue by usser1976** [jasonwynn10/PM-Beacons#16]
Don't work with Bedrock Edition v1.16.0 (protocol version 407) 

I tried to change the Protokol version xD

[Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\network\mcpe\protocol\types\NetworkInventoryAction::read(), 1 passed in /home/minecraft/plugins/MyPlugin/src/jasonwynn10/beacon/packet/InventoryTransactionPacketV2.php on line 15 and exactly 2 expected" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/types/NetworkInventoryAction" at line 90

**Comment by jasonw4331** [comment]
Tracking with #15
